Support IntimateMerger
matsumoto-kouichi/Prebid.js pull request #2
Opened 2021-06-30 03:13 UTC by matsumoto-kouichi

# テスト準備
テスト用ドメインで、IM仕様書のHook版の下記のタグを呼び出し、_im_uid.1000283でCookieを保存
```
<script async src="https://dmp.im-apps.net/scripts/im-uid-hook.js?cid=1000283"></script>
```
# テスト
1. テスト用URLへUAをスマホにして下記URLへアクセス
https://matsumoto-ad.devel.sp.gmossp-sp.jp/adtest/hb/query.php?dev=matsumoto&space_id=g917937
2.DevToolで、query.adへ、im_uidが渡る事

# 関連タスク
> https://gmomobile.backlog.jp/view/GMOAM-1753

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information

2021-06-30 04:18 UTC, KazuakiM requested changes
テストコードの修正は必要だと思います。

2021-06-30 04:18 UTC, KazuakiM commented on modules/gmosspBidAdapter.js
> +    }
getCookieの処理を見る感じ、下記で取得の方が良さそうに感じます。
取得結果がnull or stringとのことなので、nullは空文字にするとかの対応を追加で行う感じですね。
```js
const imuid = storage.getCookie('_im_uid.1000283');
```

2021-06-30 09:08 UTC, arasaki-yuki commented on modules/gmosspBidAdapter.js
> +    var imuid = '';
細かいですが、この場合 `let` の方が良いかと思います。（varは極力使わないようにしているため。）

2021-06-30 09:56 UTC, matsumoto-kouichi commented on modules/gmosspBidAdapter.js
> +    var imuid = '';
ありがとうございます。これですね。修正します。
https://www.log-stocker.com/gas/804/#GASvarletconst

2021-06-30 11:30 UTC, matsumoto-kouichi commented on modules/gmosspBidAdapter.js
> +    }
nullでも、''の空文字でも、クエリパラメータは付与されず動作しますが、
他のアダプターが直接セットしていなかったので修正しておきました。

テストコードは、とりあえず自分のIM-UIDセットしましたが、
X.XXXXXXXXXで桁合わせるとかの方が良いでしょうか？
又、テストコードが動作するか確認するには、どうすれば良いでしょうか？

2021-07-02 01:39 UTC, KazuakiM approved these changes
👍

2021-12-28 07:25 UTC, closed without merging