Add user module meta url safeframe
matsumoto-kouichi/Prebid.js pull request #5
Opened 2022-01-26 04:55 UTC by matsumoto-kouichi

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

- test parameters for validating bids
```
{
  bidder: '<bidder name>',
  params: {
    // ...
  }
}
```

Be sure to test the integration with your adserver using the [Hello World](/integrationExamples/gpt/hello_world.html) sample page.

- contact email of the adapter’s maintainer
- [ ] official adapter submission

For any changes that affect user-facing APIs or example code documented on http://prebid.org, please provide:

- A link to a PR on the docs repo at https://github.com/prebid/prebid.github.io/

## Other information

2022-01-27 11:47 UTC, KazuakiM requested changes

2022-01-27 11:47 UTC, KazuakiM commented on modules/gmosspBidAdapter.js
> +  return !!(ws.$sf && ws.$sf.ext);
`ws.$sf.ext` のチェックは不要だと思います。
`ws.$sf` があるか、ないかだけで大丈夫かと思います。

2022-01-27 11:47 UTC, KazuakiM commented on modules/gmosspBidAdapter.js
> +  let canonicalLinkContainer = window.top.document.querySelector("link[rel='canonical']");// html element containing the canonical link
後ろのコメントは不要だと思います。 
`window.top` は悩ましいです。 `og:url` 含めて悩ましいです。
`try - catch` で `window.top` 非対応のときもフォローしたほうが良いように思います。

2022-01-27 12:09 UTC, matsumoto-kouichi commented on modules/gmosspBidAdapter.js
> +  let canonicalLinkContainer = window.top.document.querySelector("link[rel='canonical']");// html element containing the canonical link
そうですね。定義してあるケースは、window.topしかないと思うので、相当悩みました。

window.topサポートしてないブラウザはなさそうですけど、エラーになるケースってあるんですかね・・
全て、try catchを指定するのも微妙だな〜と思いますが、他で入っているので仕方なく入れますか。

2022-01-28 02:05 UTC, KazuakiM commented on modules/gmosspBidAdapter.js
> +  let canonicalLinkContainer = window.top.document.querySelector("link[rel='canonical']");// html element containing the canonical link
iframeにくくわれている際にエラーとなると思います。
将来的にはSafeFrame、AMPも対応するかもです。
AMPは廃れるので放置で良いと思いますが、SafeFrameですね、問題は。

2022-01-28 02:11 UTC, KazuakiM commented on modules/gmosspBidAdapter.js
> +  let canonicalLinkContainer = window.top.document.querySelector("link[rel='canonical']");// html element containing the canonical link
SafeFrameでリファラがドメインだけになっているなどありますが、
SafeFrameという情報がわかる事で新たなアクションを起こせたらと考えています。

2022-01-31 10:29 UTC, matsumoto-kouichi commented on modules/gmosspBidAdapter.js
> +  let canonicalLinkContainer = window.top.document.querySelector("link[rel='canonical']");// html element containing the canonical link
こちら、修正しました。

2022-01-31 10:30 UTC, matsumoto-kouichi commented on modules/gmosspBidAdapter.js
> +  return !!(ws.$sf && ws.$sf.ext);
修正しました。

2022-02-01 08:09 UTC, KazuakiM requested changes

2022-02-01 08:09 UTC, KazuakiM commented on modules/gmosspBidAdapter.js
> +    url: url,
修正前のママで良さそうです。

2022-02-01 08:51 UTC, matsumoto-kouichi commented on modules/gmosspBidAdapter.js
> +    url: url,
元に戻しました。

2022-02-01 10:52 UTC, KazuakiM reviewed
メモ：
```
npx gulp build --modules=gmosspBidAdapter
cp $HOME/src/github.com/matsumoto-kouichi/Prebid.js/build/dist/prebid.js $HOME/src/github.com/gmo-am/gmossp-ad/public/adtest/hb/prebid-mabuchi.js
```

2022-02-01 11:17 UTC, KazuakiM reviewed
下記を設定して画面描画した所、リクエストパラメータが期待したものではありませんでした。ご確認をお願い致します。
```html
<link rel="canonical" href="https://trilltrill.jp/articles/1935100" />
```

2022-02-01 11:41 UTC, KazuakiM reviewed
![ss](https://user-images.githubusercontent.com/1524429/151962295-6a6f8e95-85c0-43e1-b674-14b2a14e38ed.png)

2022-02-22 03:49 UTC, KazuakiM approved these changes
👍

2022-03-01 07:16 UTC, closed without merging